version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: pv-mongo
    ports:
      - "27017:27017"   # opcional exponer afuera
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: pv-app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # por si se quiere sobreescribir la URI aquí, si no uso la del Dockerfile
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/pvdb
      # SecurityConfig usa usuarios en memoria por lo que no hace falta más.
      # posteriormente en v2.0.0 con spring.security.user.*  pasarlo acá.
    # restart: unless-stopped

volumes:
  mongo_data:
