server:
  port: 8080

spring:
  application:
    name: pv-challenge

  data:
    mongodb:
      uri: mongodb://localhost:27017/pv_challenge_db
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  users:
    - username: admin
      password: admin
      roles: ADMIN
    - username: user
      password: user
      roles: USER
